//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vendor1_Panel.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetApplication", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetApplication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int housePriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int salaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int downPercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yearsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customerId {
            get {
                return this.customerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.customerIdField, value) != true)) {
                    this.customerIdField = value;
                    this.RaisePropertyChanged("customerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int housePrice {
            get {
                return this.housePriceField;
            }
            set {
                if ((this.housePriceField.Equals(value) != true)) {
                    this.housePriceField = value;
                    this.RaisePropertyChanged("housePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int salary {
            get {
                return this.salaryField;
            }
            set {
                if ((this.salaryField.Equals(value) != true)) {
                    this.salaryField = value;
                    this.RaisePropertyChanged("salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int downPercentage {
            get {
                return this.downPercentageField;
            }
            set {
                if ((this.downPercentageField.Equals(value) != true)) {
                    this.downPercentageField = value;
                    this.RaisePropertyChanged("downPercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int years {
            get {
                return this.yearsField;
            }
            set {
                if ((this.yearsField.Equals(value) != true)) {
                    this.yearsField = value;
                    this.RaisePropertyChanged("years");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUserProfile", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetUserProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool inLawsuitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool hadBankrupcyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool hadForeclosureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool hasCreditHistoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customerId {
            get {
                return this.customerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.customerIdField, value) != true)) {
                    this.customerIdField = value;
                    this.RaisePropertyChanged("customerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool inLawsuit {
            get {
                return this.inLawsuitField;
            }
            set {
                if ((this.inLawsuitField.Equals(value) != true)) {
                    this.inLawsuitField = value;
                    this.RaisePropertyChanged("inLawsuit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool hadBankrupcy {
            get {
                return this.hadBankrupcyField;
            }
            set {
                if ((this.hadBankrupcyField.Equals(value) != true)) {
                    this.hadBankrupcyField = value;
                    this.RaisePropertyChanged("hadBankrupcy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool hadForeclosure {
            get {
                return this.hadForeclosureField;
            }
            set {
                if ((this.hadForeclosureField.Equals(value) != true)) {
                    this.hadForeclosureField = value;
                    this.RaisePropertyChanged("hadForeclosure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool hasCreditHistory {
            get {
                return this.hasCreditHistoryField;
            }
            set {
                if ((this.hasCreditHistoryField.Equals(value) != true)) {
                    this.hasCreditHistoryField = value;
                    this.RaisePropertyChanged("hasCreditHistory");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AskVendor1", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AskVendor1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rate1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customerId {
            get {
                return this.customerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.customerIdField, value) != true)) {
                    this.customerIdField = value;
                    this.RaisePropertyChanged("customerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rate1 {
            get {
                return this.rate1Field;
            }
            set {
                if ((this.rate1Field.Equals(value) != true)) {
                    this.rate1Field = value;
                    this.RaisePropertyChanged("rate1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AskVendor2", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AskVendor2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rate2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customerId {
            get {
                return this.customerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.customerIdField, value) != true)) {
                    this.customerIdField = value;
                    this.RaisePropertyChanged("customerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rate2 {
            get {
                return this.rate2Field;
            }
            set {
                if ((this.rate2Field.Equals(value) != true)) {
                    this.rate2Field = value;
                    this.RaisePropertyChanged("rate2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AskVendor3", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AskVendor3 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rate3Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customerId {
            get {
                return this.customerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.customerIdField, value) != true)) {
                    this.customerIdField = value;
                    this.RaisePropertyChanged("customerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rate3 {
            get {
                return this.rate3Field;
            }
            set {
                if ((this.rate3Field.Equals(value) != true)) {
                    this.rate3Field = value;
                    this.RaisePropertyChanged("rate3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGetApplication")]
    public interface IGetApplication {
        
        // CODEGEN: Generating message contract since the operation GetApplication is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetApplication/GetApplication", ReplyAction="http://tempuri.org/IGetApplication/GetApplicationResponse")]
        Vendor1_Panel.ServiceReference1.GetApplicationResponse GetApplication(Vendor1_Panel.ServiceReference1.GetApplicationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetApplication/GetApplication", ReplyAction="http://tempuri.org/IGetApplication/GetApplicationResponse")]
        System.Threading.Tasks.Task<Vendor1_Panel.ServiceReference1.GetApplicationResponse> GetApplicationAsync(Vendor1_Panel.ServiceReference1.GetApplicationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetApplicationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Vendor1_Panel.ServiceReference1.GetApplication GetApplication;
        
        public GetApplicationRequest() {
        }
        
        public GetApplicationRequest(Vendor1_Panel.ServiceReference1.GetApplication GetApplication) {
            this.GetApplication = GetApplication;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetApplicationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public string @string;
        
        public GetApplicationResponse() {
        }
        
        public GetApplicationResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetApplicationChannel : Vendor1_Panel.ServiceReference1.IGetApplication, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetApplicationClient : System.ServiceModel.ClientBase<Vendor1_Panel.ServiceReference1.IGetApplication>, Vendor1_Panel.ServiceReference1.IGetApplication {
        
        public GetApplicationClient() {
        }
        
        public GetApplicationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetApplicationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetApplicationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetApplicationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vendor1_Panel.ServiceReference1.GetApplicationResponse Vendor1_Panel.ServiceReference1.IGetApplication.GetApplication(Vendor1_Panel.ServiceReference1.GetApplicationRequest request) {
            return base.Channel.GetApplication(request);
        }
        
        public string GetApplication(Vendor1_Panel.ServiceReference1.GetApplication GetApplication1) {
            Vendor1_Panel.ServiceReference1.GetApplicationRequest inValue = new Vendor1_Panel.ServiceReference1.GetApplicationRequest();
            inValue.GetApplication = GetApplication1;
            Vendor1_Panel.ServiceReference1.GetApplicationResponse retVal = ((Vendor1_Panel.ServiceReference1.IGetApplication)(this)).GetApplication(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vendor1_Panel.ServiceReference1.GetApplicationResponse> Vendor1_Panel.ServiceReference1.IGetApplication.GetApplicationAsync(Vendor1_Panel.ServiceReference1.GetApplicationRequest request) {
            return base.Channel.GetApplicationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vendor1_Panel.ServiceReference1.GetApplicationResponse> GetApplicationAsync(Vendor1_Panel.ServiceReference1.GetApplication GetApplication) {
            Vendor1_Panel.ServiceReference1.GetApplicationRequest inValue = new Vendor1_Panel.ServiceReference1.GetApplicationRequest();
            inValue.GetApplication = GetApplication;
            return ((Vendor1_Panel.ServiceReference1.IGetApplication)(this)).GetApplicationAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGetUserProfile")]
    public interface IGetUserProfile {
        
        // CODEGEN: Generating message contract since the operation GetUserProfile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetUserProfile/GetUserProfile", ReplyAction="http://tempuri.org/IGetUserProfile/GetUserProfileResponse")]
        Vendor1_Panel.ServiceReference1.GetUserProfileResponse GetUserProfile(Vendor1_Panel.ServiceReference1.GetUserProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetUserProfile/GetUserProfile", ReplyAction="http://tempuri.org/IGetUserProfile/GetUserProfileResponse")]
        System.Threading.Tasks.Task<Vendor1_Panel.ServiceReference1.GetUserProfileResponse> GetUserProfileAsync(Vendor1_Panel.ServiceReference1.GetUserProfileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Vendor1_Panel.ServiceReference1.GetUserProfile GetUserProfile;
        
        public GetUserProfileRequest() {
        }
        
        public GetUserProfileRequest(Vendor1_Panel.ServiceReference1.GetUserProfile GetUserProfile) {
            this.GetUserProfile = GetUserProfile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public string @string;
        
        public GetUserProfileResponse() {
        }
        
        public GetUserProfileResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetUserProfileChannel : Vendor1_Panel.ServiceReference1.IGetUserProfile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserProfileClient : System.ServiceModel.ClientBase<Vendor1_Panel.ServiceReference1.IGetUserProfile>, Vendor1_Panel.ServiceReference1.IGetUserProfile {
        
        public GetUserProfileClient() {
        }
        
        public GetUserProfileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetUserProfileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetUserProfileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetUserProfileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vendor1_Panel.ServiceReference1.GetUserProfileResponse Vendor1_Panel.ServiceReference1.IGetUserProfile.GetUserProfile(Vendor1_Panel.ServiceReference1.GetUserProfileRequest request) {
            return base.Channel.GetUserProfile(request);
        }
        
        public string GetUserProfile(Vendor1_Panel.ServiceReference1.GetUserProfile GetUserProfile1) {
            Vendor1_Panel.ServiceReference1.GetUserProfileRequest inValue = new Vendor1_Panel.ServiceReference1.GetUserProfileRequest();
            inValue.GetUserProfile = GetUserProfile1;
            Vendor1_Panel.ServiceReference1.GetUserProfileResponse retVal = ((Vendor1_Panel.ServiceReference1.IGetUserProfile)(this)).GetUserProfile(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vendor1_Panel.ServiceReference1.GetUserProfileResponse> Vendor1_Panel.ServiceReference1.IGetUserProfile.GetUserProfileAsync(Vendor1_Panel.ServiceReference1.GetUserProfileRequest request) {
            return base.Channel.GetUserProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vendor1_Panel.ServiceReference1.GetUserProfileResponse> GetUserProfileAsync(Vendor1_Panel.ServiceReference1.GetUserProfile GetUserProfile) {
            Vendor1_Panel.ServiceReference1.GetUserProfileRequest inValue = new Vendor1_Panel.ServiceReference1.GetUserProfileRequest();
            inValue.GetUserProfile = GetUserProfile;
            return ((Vendor1_Panel.ServiceReference1.IGetUserProfile)(this)).GetUserProfileAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAskVendor1")]
    public interface IAskVendor1 {
        
        // CODEGEN: Generating message contract since the operation AskVendor1 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAskVendor1/AskVendor1", ReplyAction="http://tempuri.org/IAskVendor1/AskVendor1Response")]
        Vendor1_Panel.ServiceReference1.AskVendor1Response AskVendor1(Vendor1_Panel.ServiceReference1.AskVendor1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAskVendor1/AskVendor1", ReplyAction="http://tempuri.org/IAskVendor1/AskVendor1Response")]
        System.Threading.Tasks.Task<Vendor1_Panel.ServiceReference1.AskVendor1Response> AskVendor1Async(Vendor1_Panel.ServiceReference1.AskVendor1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AskVendor1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Vendor1_Panel.ServiceReference1.AskVendor1 AskVendor1;
        
        public AskVendor1Request() {
        }
        
        public AskVendor1Request(Vendor1_Panel.ServiceReference1.AskVendor1 AskVendor1) {
            this.AskVendor1 = AskVendor1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AskVendor1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public string @string;
        
        public AskVendor1Response() {
        }
        
        public AskVendor1Response(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAskVendor1Channel : Vendor1_Panel.ServiceReference1.IAskVendor1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AskVendor1Client : System.ServiceModel.ClientBase<Vendor1_Panel.ServiceReference1.IAskVendor1>, Vendor1_Panel.ServiceReference1.IAskVendor1 {
        
        public AskVendor1Client() {
        }
        
        public AskVendor1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AskVendor1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AskVendor1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AskVendor1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vendor1_Panel.ServiceReference1.AskVendor1Response Vendor1_Panel.ServiceReference1.IAskVendor1.AskVendor1(Vendor1_Panel.ServiceReference1.AskVendor1Request request) {
            return base.Channel.AskVendor1(request);
        }
        
        public string AskVendor1(Vendor1_Panel.ServiceReference1.AskVendor1 AskVendor11) {
            Vendor1_Panel.ServiceReference1.AskVendor1Request inValue = new Vendor1_Panel.ServiceReference1.AskVendor1Request();
            inValue.AskVendor1 = AskVendor11;
            Vendor1_Panel.ServiceReference1.AskVendor1Response retVal = ((Vendor1_Panel.ServiceReference1.IAskVendor1)(this)).AskVendor1(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vendor1_Panel.ServiceReference1.AskVendor1Response> Vendor1_Panel.ServiceReference1.IAskVendor1.AskVendor1Async(Vendor1_Panel.ServiceReference1.AskVendor1Request request) {
            return base.Channel.AskVendor1Async(request);
        }
        
        public System.Threading.Tasks.Task<Vendor1_Panel.ServiceReference1.AskVendor1Response> AskVendor1Async(Vendor1_Panel.ServiceReference1.AskVendor1 AskVendor1) {
            Vendor1_Panel.ServiceReference1.AskVendor1Request inValue = new Vendor1_Panel.ServiceReference1.AskVendor1Request();
            inValue.AskVendor1 = AskVendor1;
            return ((Vendor1_Panel.ServiceReference1.IAskVendor1)(this)).AskVendor1Async(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAskVendor2")]
    public interface IAskVendor2 {
        
        // CODEGEN: Generating message contract since the operation AskVendor2 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAskVendor2/AskVendor2", ReplyAction="http://tempuri.org/IAskVendor2/AskVendor2Response")]
        Vendor1_Panel.ServiceReference1.AskVendor2Response AskVendor2(Vendor1_Panel.ServiceReference1.AskVendor2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAskVendor2/AskVendor2", ReplyAction="http://tempuri.org/IAskVendor2/AskVendor2Response")]
        System.Threading.Tasks.Task<Vendor1_Panel.ServiceReference1.AskVendor2Response> AskVendor2Async(Vendor1_Panel.ServiceReference1.AskVendor2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AskVendor2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Vendor1_Panel.ServiceReference1.AskVendor2 AskVendor2;
        
        public AskVendor2Request() {
        }
        
        public AskVendor2Request(Vendor1_Panel.ServiceReference1.AskVendor2 AskVendor2) {
            this.AskVendor2 = AskVendor2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AskVendor2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public string @string;
        
        public AskVendor2Response() {
        }
        
        public AskVendor2Response(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAskVendor2Channel : Vendor1_Panel.ServiceReference1.IAskVendor2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AskVendor2Client : System.ServiceModel.ClientBase<Vendor1_Panel.ServiceReference1.IAskVendor2>, Vendor1_Panel.ServiceReference1.IAskVendor2 {
        
        public AskVendor2Client() {
        }
        
        public AskVendor2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AskVendor2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AskVendor2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AskVendor2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vendor1_Panel.ServiceReference1.AskVendor2Response Vendor1_Panel.ServiceReference1.IAskVendor2.AskVendor2(Vendor1_Panel.ServiceReference1.AskVendor2Request request) {
            return base.Channel.AskVendor2(request);
        }
        
        public string AskVendor2(Vendor1_Panel.ServiceReference1.AskVendor2 AskVendor21) {
            Vendor1_Panel.ServiceReference1.AskVendor2Request inValue = new Vendor1_Panel.ServiceReference1.AskVendor2Request();
            inValue.AskVendor2 = AskVendor21;
            Vendor1_Panel.ServiceReference1.AskVendor2Response retVal = ((Vendor1_Panel.ServiceReference1.IAskVendor2)(this)).AskVendor2(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vendor1_Panel.ServiceReference1.AskVendor2Response> Vendor1_Panel.ServiceReference1.IAskVendor2.AskVendor2Async(Vendor1_Panel.ServiceReference1.AskVendor2Request request) {
            return base.Channel.AskVendor2Async(request);
        }
        
        public System.Threading.Tasks.Task<Vendor1_Panel.ServiceReference1.AskVendor2Response> AskVendor2Async(Vendor1_Panel.ServiceReference1.AskVendor2 AskVendor2) {
            Vendor1_Panel.ServiceReference1.AskVendor2Request inValue = new Vendor1_Panel.ServiceReference1.AskVendor2Request();
            inValue.AskVendor2 = AskVendor2;
            return ((Vendor1_Panel.ServiceReference1.IAskVendor2)(this)).AskVendor2Async(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAskVendor3")]
    public interface IAskVendor3 {
        
        // CODEGEN: Generating message contract since the operation AskVendor3 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="http://tempuri.org/IAskVendor3/AskVendor3Response")]
        Vendor1_Panel.ServiceReference1.AskVendor3Response AskVendor3(Vendor1_Panel.ServiceReference1.AskVendor3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="http://tempuri.org/IAskVendor3/AskVendor3Response")]
        System.Threading.Tasks.Task<Vendor1_Panel.ServiceReference1.AskVendor3Response> AskVendor3Async(Vendor1_Panel.ServiceReference1.AskVendor3Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AskVendor3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Vendor1_Panel.ServiceReference1.AskVendor3 AskVendor3;
        
        public AskVendor3Request() {
        }
        
        public AskVendor3Request(Vendor1_Panel.ServiceReference1.AskVendor3 AskVendor3) {
            this.AskVendor3 = AskVendor3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AskVendor3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public string @string;
        
        public AskVendor3Response() {
        }
        
        public AskVendor3Response(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAskVendor3Channel : Vendor1_Panel.ServiceReference1.IAskVendor3, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AskVendor3Client : System.ServiceModel.ClientBase<Vendor1_Panel.ServiceReference1.IAskVendor3>, Vendor1_Panel.ServiceReference1.IAskVendor3 {
        
        public AskVendor3Client() {
        }
        
        public AskVendor3Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AskVendor3Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AskVendor3Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AskVendor3Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vendor1_Panel.ServiceReference1.AskVendor3Response Vendor1_Panel.ServiceReference1.IAskVendor3.AskVendor3(Vendor1_Panel.ServiceReference1.AskVendor3Request request) {
            return base.Channel.AskVendor3(request);
        }
        
        public string AskVendor3(Vendor1_Panel.ServiceReference1.AskVendor3 AskVendor31) {
            Vendor1_Panel.ServiceReference1.AskVendor3Request inValue = new Vendor1_Panel.ServiceReference1.AskVendor3Request();
            inValue.AskVendor3 = AskVendor31;
            Vendor1_Panel.ServiceReference1.AskVendor3Response retVal = ((Vendor1_Panel.ServiceReference1.IAskVendor3)(this)).AskVendor3(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vendor1_Panel.ServiceReference1.AskVendor3Response> Vendor1_Panel.ServiceReference1.IAskVendor3.AskVendor3Async(Vendor1_Panel.ServiceReference1.AskVendor3Request request) {
            return base.Channel.AskVendor3Async(request);
        }
        
        public System.Threading.Tasks.Task<Vendor1_Panel.ServiceReference1.AskVendor3Response> AskVendor3Async(Vendor1_Panel.ServiceReference1.AskVendor3 AskVendor3) {
            Vendor1_Panel.ServiceReference1.AskVendor3Request inValue = new Vendor1_Panel.ServiceReference1.AskVendor3Request();
            inValue.AskVendor3 = AskVendor3;
            return ((Vendor1_Panel.ServiceReference1.IAskVendor3)(this)).AskVendor3Async(inValue);
        }
    }
}
