//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPersistenceWF.ServiceReference3 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenerateRandom", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GenerateRandom : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckNumber", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CheckNumber : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IGenerateRandom")]
    public interface IGenerateRandom {
        
        // CODEGEN: Generating message contract since the operation GenerateRandom is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenerateRandom/GenerateRandom", ReplyAction="http://tempuri.org/IGenerateRandom/GenerateRandomResponse")]
        testPersistenceWF.ServiceReference3.GenerateRandomResponse GenerateRandom(testPersistenceWF.ServiceReference3.GenerateRandomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenerateRandom/GenerateRandom", ReplyAction="http://tempuri.org/IGenerateRandom/GenerateRandomResponse")]
        System.Threading.Tasks.Task<testPersistenceWF.ServiceReference3.GenerateRandomResponse> GenerateRandomAsync(testPersistenceWF.ServiceReference3.GenerateRandomRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateRandomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public testPersistenceWF.ServiceReference3.GenerateRandom GenerateRandom;
        
        public GenerateRandomRequest() {
        }
        
        public GenerateRandomRequest(testPersistenceWF.ServiceReference3.GenerateRandom GenerateRandom) {
            this.GenerateRandom = GenerateRandom;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateRandomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public string @string;
        
        public GenerateRandomResponse() {
        }
        
        public GenerateRandomResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGenerateRandomChannel : testPersistenceWF.ServiceReference3.IGenerateRandom, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenerateRandomClient : System.ServiceModel.ClientBase<testPersistenceWF.ServiceReference3.IGenerateRandom>, testPersistenceWF.ServiceReference3.IGenerateRandom {
        
        public GenerateRandomClient() {
        }
        
        public GenerateRandomClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GenerateRandomClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenerateRandomClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenerateRandomClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testPersistenceWF.ServiceReference3.GenerateRandomResponse testPersistenceWF.ServiceReference3.IGenerateRandom.GenerateRandom(testPersistenceWF.ServiceReference3.GenerateRandomRequest request) {
            return base.Channel.GenerateRandom(request);
        }
        
        public string GenerateRandom(testPersistenceWF.ServiceReference3.GenerateRandom GenerateRandom1) {
            testPersistenceWF.ServiceReference3.GenerateRandomRequest inValue = new testPersistenceWF.ServiceReference3.GenerateRandomRequest();
            inValue.GenerateRandom = GenerateRandom1;
            testPersistenceWF.ServiceReference3.GenerateRandomResponse retVal = ((testPersistenceWF.ServiceReference3.IGenerateRandom)(this)).GenerateRandom(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<testPersistenceWF.ServiceReference3.GenerateRandomResponse> testPersistenceWF.ServiceReference3.IGenerateRandom.GenerateRandomAsync(testPersistenceWF.ServiceReference3.GenerateRandomRequest request) {
            return base.Channel.GenerateRandomAsync(request);
        }
        
        public System.Threading.Tasks.Task<testPersistenceWF.ServiceReference3.GenerateRandomResponse> GenerateRandomAsync(testPersistenceWF.ServiceReference3.GenerateRandom GenerateRandom) {
            testPersistenceWF.ServiceReference3.GenerateRandomRequest inValue = new testPersistenceWF.ServiceReference3.GenerateRandomRequest();
            inValue.GenerateRandom = GenerateRandom;
            return ((testPersistenceWF.ServiceReference3.IGenerateRandom)(this)).GenerateRandomAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.ICheckNumber")]
    public interface ICheckNumber {
        
        // CODEGEN: Generating message contract since the operation CheckNumber is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckNumber/CheckNumber", ReplyAction="http://tempuri.org/ICheckNumber/CheckNumberResponse")]
        testPersistenceWF.ServiceReference3.CheckNumberResponse CheckNumber(testPersistenceWF.ServiceReference3.CheckNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckNumber/CheckNumber", ReplyAction="http://tempuri.org/ICheckNumber/CheckNumberResponse")]
        System.Threading.Tasks.Task<testPersistenceWF.ServiceReference3.CheckNumberResponse> CheckNumberAsync(testPersistenceWF.ServiceReference3.CheckNumberRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public testPersistenceWF.ServiceReference3.CheckNumber CheckNumber;
        
        public CheckNumberRequest() {
        }
        
        public CheckNumberRequest(testPersistenceWF.ServiceReference3.CheckNumber CheckNumber) {
            this.CheckNumber = CheckNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public string @string;
        
        public CheckNumberResponse() {
        }
        
        public CheckNumberResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICheckNumberChannel : testPersistenceWF.ServiceReference3.ICheckNumber, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckNumberClient : System.ServiceModel.ClientBase<testPersistenceWF.ServiceReference3.ICheckNumber>, testPersistenceWF.ServiceReference3.ICheckNumber {
        
        public CheckNumberClient() {
        }
        
        public CheckNumberClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckNumberClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckNumberClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckNumberClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testPersistenceWF.ServiceReference3.CheckNumberResponse testPersistenceWF.ServiceReference3.ICheckNumber.CheckNumber(testPersistenceWF.ServiceReference3.CheckNumberRequest request) {
            return base.Channel.CheckNumber(request);
        }
        
        public string CheckNumber(testPersistenceWF.ServiceReference3.CheckNumber CheckNumber1) {
            testPersistenceWF.ServiceReference3.CheckNumberRequest inValue = new testPersistenceWF.ServiceReference3.CheckNumberRequest();
            inValue.CheckNumber = CheckNumber1;
            testPersistenceWF.ServiceReference3.CheckNumberResponse retVal = ((testPersistenceWF.ServiceReference3.ICheckNumber)(this)).CheckNumber(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<testPersistenceWF.ServiceReference3.CheckNumberResponse> testPersistenceWF.ServiceReference3.ICheckNumber.CheckNumberAsync(testPersistenceWF.ServiceReference3.CheckNumberRequest request) {
            return base.Channel.CheckNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<testPersistenceWF.ServiceReference3.CheckNumberResponse> CheckNumberAsync(testPersistenceWF.ServiceReference3.CheckNumber CheckNumber) {
            testPersistenceWF.ServiceReference3.CheckNumberRequest inValue = new testPersistenceWF.ServiceReference3.CheckNumberRequest();
            inValue.CheckNumber = CheckNumber;
            return ((testPersistenceWF.ServiceReference3.ICheckNumber)(this)).CheckNumberAsync(inValue);
        }
    }
}
