//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF4_client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IEvaluateMortage")]
    public interface IEvaluateMortage {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvaluateMortage/EvaluateMortage", ReplyAction="http://tempuri.org/IEvaluateMortage/EvaluateMortageResponse")]
        WF4_client.ServiceReference1.EvaluateMortageResponse EvaluateMortage(WF4_client.ServiceReference1.EvaluateMortageRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvaluateMortage/EvaluateMortage", ReplyAction="http://tempuri.org/IEvaluateMortage/EvaluateMortageResponse")]
        System.Threading.Tasks.Task<WF4_client.ServiceReference1.EvaluateMortageResponse> EvaluateMortageAsync(WF4_client.ServiceReference1.EvaluateMortageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EvaluateMortage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EvaluateMortageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string customerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int housePrice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int downPayment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int years;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int salary;
        
        public EvaluateMortageRequest() {
        }
        
        public EvaluateMortageRequest(string customerCode, int housePrice, int downPayment, int years, int salary) {
            this.customerCode = customerCode;
            this.housePrice = housePrice;
            this.downPayment = downPayment;
            this.years = years;
            this.salary = salary;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EvaluateMortageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EvaluateMortageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int frate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public EvaluateMortageResponse() {
        }
        
        public EvaluateMortageResponse(int frate, string message) {
            this.frate = frate;
            this.message = message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEvaluateMortageChannel : WF4_client.ServiceReference1.IEvaluateMortage, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EvaluateMortageClient : System.ServiceModel.ClientBase<WF4_client.ServiceReference1.IEvaluateMortage>, WF4_client.ServiceReference1.IEvaluateMortage {
        
        public EvaluateMortageClient() {
        }
        
        public EvaluateMortageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EvaluateMortageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvaluateMortageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvaluateMortageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WF4_client.ServiceReference1.EvaluateMortageResponse WF4_client.ServiceReference1.IEvaluateMortage.EvaluateMortage(WF4_client.ServiceReference1.EvaluateMortageRequest request) {
            return base.Channel.EvaluateMortage(request);
        }
        
        public int EvaluateMortage(string customerCode, int housePrice, int downPayment, int years, int salary, out string message) {
            WF4_client.ServiceReference1.EvaluateMortageRequest inValue = new WF4_client.ServiceReference1.EvaluateMortageRequest();
            inValue.customerCode = customerCode;
            inValue.housePrice = housePrice;
            inValue.downPayment = downPayment;
            inValue.years = years;
            inValue.salary = salary;
            WF4_client.ServiceReference1.EvaluateMortageResponse retVal = ((WF4_client.ServiceReference1.IEvaluateMortage)(this)).EvaluateMortage(inValue);
            message = retVal.message;
            return retVal.frate;
        }
        
        public System.Threading.Tasks.Task<WF4_client.ServiceReference1.EvaluateMortageResponse> EvaluateMortageAsync(WF4_client.ServiceReference1.EvaluateMortageRequest request) {
            return base.Channel.EvaluateMortageAsync(request);
        }
    }
}
